<?php

namespace svsoft\yii\modules\admin\widgets;

use svsoft\yii\modules\admin\components\BaseAdminModule;
use Yii;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\helpers\Html;

/**
 * Class Menu
 * Theme menu widget.
 */
class Menu extends \dmstr\widgets\Menu
{

    public function init()
    {
        //$modules = Yii::$app->getModule('modules')->adminModules;

        $modules = Yii::$app->getModule('admin')->modules;

        $adminModule = Yii::$app->getModule('admin');

        foreach($modules as $id=>$module)
        {
            $module = $adminModule->getModule($id);
            if ($module && ($module instanceof BaseAdminModule))
            {
                if ($module->adminMenu)
                    $this->items = ArrayHelper::merge($this->items, $module->adminMenu);

            }
        }

        parent::init(); // TODO: Change the autogenerated stub
    }
}
