<?php

namespace svsoft\yii\modules\properties\models\forms\types;

use svsoft\yii\modules\properties\models\forms\PropertyValueForm;

/**
 * Class IntegerValue
 *
 * @package svsoft\yii\modules\properties\components\types
 */
class IntegerValue extends PropertyValueForm
{
    public function getColumnName()
    {
        return 'int_value';
    }

    function rules()
    {
        $rules = parent::rules(); // TODO: Change the autogenerated stub
        $rules[] = [['value'], 'integer'];


        return $rules;
    }
}