<?php

namespace svsoft\yii\modules\properties\models\forms\types;

use svsoft\yii\modules\properties\models\forms\PropertyForm;

/**
 * Class PropertyString
 *
 * @package svsoft\yii\modules\properties\components\types
 */
class PropertyString extends PropertyForm
{
    function rules()
    {
        $rules = parent::rules(); // TODO: Change the autogenerated stub

        // Для множественного
        $rules[] = ['values', 'each', 'rule' => ['string', 'max' => 255]];
        // Для немножественного
        $rules[] = ['value', 'string', 'max' => 255];

        return $rules;
    }
}