<?php

namespace svsoft\yii\modules\properties\models\forms\types;

use svsoft\yii\modules\properties\models\forms\PropertyForm;

/**
 * Class PropertyInteger
 *
 * @package svsoft\yii\modules\properties\components\types
 */
class PropertyInteger extends PropertyForm
{
    function rules()
    {
        $rules = parent::rules(); // TODO: Change the autogenerated stub

        // Для множественного
        $rules[] = ['values', 'each', 'rule' => ['integer']];
        // Для немножественного
        $rules[] = ['value', 'integer'];

        return $rules;
    }
}