<?php


namespace svsoft\yii\modules\catalog\query;


use svsoft\yii\modules\catalog\models\Category;
use yii\db\ActiveQuery;

class CategoryQuery extends ActiveQuery
{
    public function active()
    {
        return $this->andWhere(['active'=>true]);
    }

    /**
     * @param null $db
     *
     * @return Category
     */
    public function one($db = null)
    {
        return parent::one($db); // TODO: Change the autogenerated stub
    }

    /**
     * @param null $db
     *
     * @return Category[]
     */
    public function all($db = null)
    {
        return parent::all($db); // TODO: Change the autogenerated stub
    }
}