<?php
namespace svsoft\yii\behaviors;


use Yii;
use yii\base\Component;
use yii\helpers\Html;

/**
 * This is the model class for table "article".
 *
 */
class EncodeAttribute extends Component
{
    public $owner;

    function __get($name)
    {
        return Html::encode($this->owner->__get($name)); // TODO: Change the autogenerated stub
    }

}
