<?php

namespace svsoft\yii\modules\main\admin\widgets;

use Yii;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\helpers\Html;

/**
 * Class Menu
 * Theme menu widget.
 */
class Menu extends \dmstr\widgets\Menu
{

    public function init()
    {
        $modules = Yii::$app->getModule('main')->adminModules;

        foreach($modules as $id)
        {
            $this->items = ArrayHelper::merge($this->items, Yii::$app->getModule($id)->getModule('admin')->adminMenu);
        }

        parent::init(); // TODO: Change the autogenerated stub
    }
}
