<?php

namespace svsoft\yii\modules\main\admin\widgets;

use Yii;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\helpers\Html;

/**
 * Class Menu
 * Theme menu widget.
 */
class Menu extends \dmstr\widgets\Menu
{

    public function init()
    {
        $modules = Yii::$app->getModule('main')->adminModules;

        foreach($modules as $id)
        {
            //var_dump($id);

            if (!$module = Yii::$app->getModule($id))
                continue;

            if (!$adminModule = $module->getModule('admin'))
                continue;

            if (!$adminModule->adminMenu)
                continue;

            $this->items = ArrayHelper::merge($this->items, $adminModule->adminMenu);
        }

        parent::init(); // TODO: Change the autogenerated stub
    }
}
